# Generated by Django 2.1 on 2020-12-21 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiondao',
            old_name='questionInText',
            new_name='questionText',
        ),
    ]
