# Generated by Django 2.1 on 2021-01-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20201223_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondao',
            name='session',
        ),
        migrations.AddField(
            model_name='questiondao',
            name='classType',
            field=models.CharField(choices=[('First Class', 1), ('Second Class', 2), ('Third Class', 3), ('Forth Class', 4), ('Fifth Class', 5), ('Sixth Class', 6)], default='First Class', max_length=15),
        ),
        migrations.AlterField(
            model_name='questiondao',
            name='answer',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='questiondao',
            name='question',
            field=models.CharField(max_length=80),
        ),
    ]
